name: "Publish"

on:
  push:
  repository_dispatch:
    types: [trigger]  # Optional: for two-way sync

jobs:
  publish_to_hashnode:
    runs-on: ubuntu-latest
    name: Hashnode Github Sync
    permissions:
      contents: write  # Required if using two-way sync, not necessary for one-way

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Debug - Output changed files
        run: |
          echo "Added files: ${{steps.changed-files.outputs.added_files}}"
          echo "Modified files: ${{steps.changed-files.outputs.modified_files}}"
          echo "Deleted files: ${{steps.changed-files.outputs.deleted_files}}"
      
      - name: Filter markdown files
        run: |
          echo "::set-output name=added_files::$(echo "${{steps.changed-files.outputs.added_files}}" | grep '\.md$')" >> $GITHUB_OUTPUT
          echo "::set-output name=modified_files::$(echo "${{steps.changed-files.outputs.modified_files}}" | grep '\.md$')" >> $GITHUB_OUTPUT
          echo "::set-output name=deleted_files::$(echo "${{steps.changed-files.outputs.deleted_files}}" | grep '\.md$')" >> $GITHUB_OUTPUT

      - name: Hashnode Github Sync
        uses: iammarmirza/hashnode-github-sync@v1.5
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
        with:
          hashnode_host: "kaustubhrai.hashnode.dev"  # Replace with your Hashnode host name
          hashnode_token: ${{ secrets.HASHNODE_TOKEN }}  # Add your Hashnode secret token in GitHub Secrets
          added_files: ${{steps.changed-files.outputs.added_files}}
          modified_files: ${{steps.changed-files.outputs.modified_files}}
          deleted_files: ${{steps.changed-files.outputs.deleted_files}}
